project_id   = "<REEMPLAZAR_PROJECT_ID>"
region       = "us-central1"
service_name = "eqx-backend-prod"
image_url    = "<REEMPLAZAR_IMAGE_URL>"
secret_key   = "<REEMPLAZAR_SECRET_KEY>"
jwt_algorithm = "HS256"
