project_id   = "<REEMPLAZAR_PROJECT_ID>"
region       = "us-central1"
service_name = "eqx-backend-dev"
image_url    = "<REEMPLAZAR_IMAGE_URL>"
secret_key   = "dev-secret-key-demo"
jwt_algorithm = "HS256"
project_name = "eqx-demo-project"
org_id       = "<REEMPLAZAR_ORG_ID>"
